SELECT I.SUMMARY AS TASK, L.NAME AS LIST_NAME
FROM ISSUES I
JOIN ISSUELISTS L ON I.ISSUESLIST_ID = L.ID
ORDER BY L.NAME, I.SUMMARY



SELECT U.FIRSTNAME, U.LASTNAME, I.SUMMARY AS TASK
FROM ISSUES I
JOIN USERS U ON I.USER_ID_ASSIGNEDTO = U.ID
ORDER BY U.LASTNAME, U.FIRSTNAME, I.SUMMARY



SELECT U.FIRSTNAME, U.LASTNAME, COUNT(*) AS TASKS_NUMBER
FROM ISSUES I JOIN USERS U ON U.ID = I.USER_ID_ASSIGNEDTO
GROUP BY U.LASTNAME
ORDER BY TASKS_NUMBER DESC;