CREATE TABLE BOOKS_AUD (
EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
EVENT_DATE DATETIME NOT NULL,
EVENT_TYPE VARCHAR(10) DEFAULT NULL,
BOOK_ID INT(11),
OLD_TITLE VARCHAR(255),
NEW_TITLE VARCHAR(255),
OLD_PUBYEAR INT(4),
NEW_PUBYEAR INT(4),
PRIMARY KEY (`EVENT_ID`)
);

CREATE TABLE READERS_AUD (
EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
EVENT_DATE DATETIME NOT NULL,
EVENT_TYPE VARCHAR(10) DEFAULT NULL,
READER_ID INT(11),
OLD_FIRSTNAME VARCHAR(255),
NEW_FIRSTNAME VARCHAR(255),
OLD_LASTNAME VARCHAR(255),
NEW_LASTNAME VARCHAR(255),
OLD_PESELID VARCHAR(11),
NEW_PESELID VARCHAR(11),
PRIMARY KEY (`EVENT_ID`)
);

DELIMITER $$

CREATE TRIGGER BOOKS_INSERT AFTER INSERT ON BOOKS
FOR EACH ROW
BEGIN
	INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_PUBYEAR)
    VALUES (CURTIME(), "INSERT", NEW.BOOK_ID, NEW.TITLE, NEW.PUBYEAR);
END $$

CREATE TRIGGER BOOKS_DELETE AFTER DELETE ON BOOKS
FOR EACH ROW
BEGIN
	INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID)
	VALUES (CURTIME(), "DELETE", OLD.BOOK_ID);
END $$

CREATE TRIGGER BOOKS_UPDATE AFTER UPDATE ON BOOKS
FOR EACH ROW
BEGIN
	INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_PUBYEAR, OLD_TITLE, OLD_PUBYEAR)
    VALUES (CURTIME(), "UPDATE", OLD.BOOK_ID, NEW.TITLE, NEW.PUBYEAR, OLD.TITLE, OLD.PUBYEAR);
END $$

CREATE TRIGGER READERS_INSERT AFTER INSERT ON READERS
FOR EACH ROW
BEGIN
	INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, NEW_FIRSTNAME, NEW_LASTNAME, NEW_PESELID)
    VALUES (CURTIME(), "INSERT", NEW.READER_ID, NEW.FIRSTNAME, NEW.LASTNAME, NEW.PESELID);
END $$

CREATE TRIGGER READERS_DELETE AFTER DELETE ON READERS
FOR EACH ROW
BEGIN
	INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID)
    VALUES (CURTIME(), "DELETE", OLD.READER_ID);
END $$

CREATE TRIGGER READERS_UPDATE AFTER UPDATE ON READERS
FOR EACH ROW
BEGIN
	INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, NEW_FIRSTNAME, NEW_LASTNAME, NEW_PESELID,
    OLD_FIRSTNAME, OLD_LASTNAME, OLD_PESELID)
    VALUES (CURTIME(), "UPDATE", OLD.READER_ID, NEW.FIRSTNAME, NEW.LASTNAME, NEW.PESELID, OLD.FIRSTNAME, OLD.LASTNAME, OLD.PESELID);
END $$

DELIMITER ;