EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = "John";

CREATE INDEX READERNAMES ON READERS (FIRSTNAME, LASTNAME);

CREATE INDEX BOOKTITLE ON BOOKS (TITLE);

EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = "John";